#!/bin/bash

TOKEN='771d585124ab9c6c13fe7d6f2d6ad1e4'
USER_ID='7'
OLD_PW='defcon'
NEW_PW='defcon1'

BASE_URL="http://10.13.105.91:3000"
URL="${BASE_URL}/change-password/${USER_ID}"

url() {

    CONTENT_TYPE="application/x-www-form-urlencoded"

    curl ${URL}\
    --silent \
    --request PATCH \
    --header "Content-Type: ${CONTENT_TYPE}" \
    --header "Authorization: Token token=${TOKEN}" \
    --data-urlencode "password[old]=${OLD_PW}" \
    --data-urlencode "password[new]=${NEW_PW}"
}

json() {

#  --header "Authorization: Token token=${TOKEN}" \
echo

}

url

# data output from curl doesn't have a trailing newline
echo
