#!/bin/bash

EMAIL='defcon'
PASSWORD='defcon'

BASE_URL="http://10.13.105.91:3000"
URL="${BASE_URL}/sign-up"
#URL="http://httpbin.org/post"

url() {

  CONTENT_TYPE="application/x-www-form-urlencoded"

}

json() {

  CONTENT_TYPE="application/json"

  curl ${URL} \
  --include \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data "{
    \"credentials\": {
      \"email\": \"${EMAIL}\",
      \"password\": \"${PASSWORD}\"
    }
  }"

}

json

echo
