#!/bin/bash

EMAIL='defcon'
PASSWORD='defcon1'

BASE_URL="http://10.13.105.91:3000"
URL="${BASE_URL}/sign-in"

url() {
  CONTENT_TYPE="application/x-www-form-urlencoded"

  curl ${URL}\
  --silent \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data-urlencoded "crendentials[email]=${EMAIL}"\
  --data-urlencoded "crendentials[password]=${PASSWORD}"
}

json() {
  CONTENT_TYPE="application/json"

  curl ${URL}\
  --silent \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data "{
      \"credentials\": {
      \"email\": \"${EMAIL}\",
      \"password\": \"${PASSWORD}\"
    }
  }"

}

json

echo
